--# -*- coding: utf-8 -*-
--# DISTRIBUTION STATEMENT A. Approved for public release. Distribution is unlimited.

--# This material is based upon work supported under Air Force Contract No. FA8702-15-D-0001.
--# Any opinions,findings, conclusions or recommendations expressed in this material are those
--# of the author(s) and do not necessarily reflect the views of the Centers for Disease Control.

--# (c) 2021 Massachusetts Institute of Technology.

--# The software/firmware is provided to you on an As-Is basis

--# Delivered to the U.S. Government with Unlimited Rights, as defined in DFARS Part 252.227-7013
--# or 7014 (Feb 2014). Notwithstanding any copyright notice, U.S. Government rights in this work
--# are defined by DFARS 252.227-7013 or DFARS 252.227-7014 as detailed above. Use of this work
--# other than as specifically authorized by the U.S. Government may violate any copyrights that
--# exist in this work.

--# Copyright (c) 2021 Massachusetts Institute of Technology
--# SPDX short identifier: MIT

--# Developed as part of: SimAEN, 2021

CREATE TABLE aggregate_data (
    id SERIAL PRIMARY KEY,
    r double precision,
    cases_prevented integer,
    isolated_due_to_en integer,
    false_quar_due_to_en integer,
    infected integer[],
    pos_and_quar integer[],
    quar_and_not_infected integer[],
    infected_and_aen integer[],
    infected_and_mct integer[],
    infected_and_both integer[],
    infected_and_pos integer[],
    infected_and_none integer[],
    aen_followup_calls integer[],
    mct_calls integer[],
    other_calls integer[],
    aen_triggered_tests integer[],
    mct_triggered_tests integer[],
    symptomatic_tests integer[],
    pos_aen integer[],
    pos_mct integer[],
    pos_both integer[],
    pos_none integer[],
    pos_aen_sym integer[],
    pos_mct_sym integer[],
    pos_both_sym integer[],
    pos_none_sym integer[],
    pos_aen_asym integer[],
    pos_mct_asym integer[],
    pos_both_asym integer[],
    pos_none_asym integer[],
    neg_aen integer[],
    neg_mct integer[],
    neg_both integer[],
    neg_none integer[],
    quar_aen integer[],
    quar_mct integer[],
    quar_both integer[],
    quar_none integer[]
);


CREATE TABLE parameters (
    id BIGSERIAL PRIMARY KEY,
    config_group_num integer,
    num_worlds double precision,
    starting_cases double precision,
    end_day bigint,
    max_num_current_cases bigint,
    mean_latent_period double precision,
    sd_latent_period double precision,
    recovery_length double precision,
    p_asymptomatic_rate double precision,
    p_transmission_asymptomatic_given_no_masks double precision,
    p_transmission_presymptomatic_given_no_masks double precision,
    p_transmission_symptomatic_given_no_masks double precision,
    p_test_given_call double precision,
    p_test_baseline double precision,
    p_test_given_notification double precision,
    p_test_given_symptomatic double precision,
    test_delay double precision,
    test_delay_sigma double precision,
    daily_test_capacity double precision,
    p_positive_test_given_exposed double precision,
    p_positive_test_given_presymptomatic double precision,
    p_positive_test_given_symptomatic double precision,
    p_positive_test_given_asymptomatic double precision,
    p_running_app double precision,
    p_app_detects_generator double precision,
    false_discovery_rate double precision,
    p_upload_key_given_positive_test double precision,
    key_upload_requires_call double precision,
    p_successful_call_unanticipated double precision,
    p_successful_call_anticipated double precision,
    p_identify_individual_using_manual_contact_tracing double precision,
    max_contacts_recalled double precision,
    n_contact_tracers double precision,
    work_day_length double precision,
    max_call_attempts double precision,
    missed_call_time double precision,
    index_trace_call_time double precision,
    alert_call_time double precision,
    key_upload_call_time double precision,
    p_start_min double precision,
    p_start_mod double precision,
    p_start_max double precision,
    p_mask_given_norm double precision,
    p_mask_given_min double precision,
    p_mask_given_mod double precision,
    p_mask_given_max double precision,
    mask_effect double precision,
    p_contact_public_health_after_positive_test double precision,
    mean_total_contacts double precision,
    sigma_total_contacts double precision,
    mean_new_cases double precision,
    sigma_new_cases double precision,
    mean_new_cases_minimal double precision,
    sigma_new_cases_minimal double precision,
    mean_new_cases_moderate double precision,
    sigma_new_cases_moderate double precision,
    mean_new_cases_maximal double precision,
    sigma_new_cases_maximal double precision,
    p_starting_behavior_after_negative_test_no_symptoms double precision,
    p_maximal_restriction_given_symptomatic double precision,
    p_moderate_restriction_given_symptomatic double precision,
    p_minimal_restriction_given_symptomatic double precision,
    p_maximal_restriction_given_positive_test double precision,
    p_moderate_restriction_given_positive_test double precision,
    p_minimal_restriction_given_positive_test double precision,
    p_maximal_restriction_given_aen_notification double precision,
    p_moderate_restriction_given_aen_notification double precision,
    p_minimal_restriction_given_aen_notification double precision,
    p_vaccinated double precision,
    vaccinated_people_can_spread_asymptomatically double precision,
    mean_incubation_period double precision,
    sd_incubation_period double precision,
    p_contact_public_health_after_aen_notification double precision,
    p_maximal_restriction_given_ph_call double precision,
    p_moderate_restriction_given_ph_call double precision,
    p_minimal_restriction_given_ph_call double precision
);

CREATE INDEX parameters_search_params_idx ON parameters USING btree (
    id,
    starting_cases,
    test_delay,
    p_running_app,
    key_upload_requires_call,
    n_contact_tracers,
    mean_new_cases,
    mean_total_contacts,
    p_maximal_restriction_given_ph_call,
    p_maximal_restriction_given_aen_notification,
    p_vaccinated,
    p_mask_given_norm,
    p_app_detects_generator,
    false_discovery_rate);


CREATE TABLE run_data (
    id BIGSERIAL PRIMARY KEY,
    config_group_num integer,
    run_length integer,
    infected integer[],
    pos_and_quar integer[],
    cases_prevented integer[],
    quar_and_not_infected integer[],
    infected_and_aen integer[],
    infected_and_mct integer[],
    infected_and_both integer[],
    infected_and_pos integer[],
    infected_and_none integer[],
    aen_followup_calls integer[],
    mct_calls integer[],
    other_calls integer[],
    aen_triggered_tests integer[],
    mct_triggered_tests integer[],
    symptomatic_tests integer[],
    pos_aen integer[],
    pos_mct integer[],
    pos_both integer[],
    pos_none integer[],
    pos_aen_sym integer[],
    pos_mct_sym integer[],
    pos_both_sym integer[],
    pos_none_sym integer[],
    pos_aen_asym integer[],
    pos_mct_asym integer[],
    pos_both_asym integer[],
    pos_none_asym integer[],
    neg_aen integer[],
    neg_mct integer[],
    neg_both integer[],
    neg_none integer[],
    quar_aen integer[],
    quar_mct integer[],
    quar_both integer[],
    quar_none integer[],
    r double precision[]
);
