#!/usr/bin/env groovy

/*
# DISTRIBUTION STATEMENT A. Approved for public release. Distribution is unlimited.

# This material is based upon work supported under Air Force Contract No. FA8702-15-D-0001.
# Any opinions,findings, conclusions or recommendations expressed in this material are those
# of the author(s) and do not necessarily reflect the views of the Centers for Disease Control.

# (c) 2021 Massachusetts Institute of Technology.

# The software/firmware is provided to you on an As-Is basis

# Delivered to the U.S. Government with Unlimited Rights, as defined in DFARS Part 252.227-7013
# or 7014 (Feb 2014). Notwithstanding any copyright notice, U.S. Government rights in this work
# are defined by DFARS 252.227-7013 or DFARS 252.227-7014 as detailed above. Use of this work
# other than as specifically authorized by the U.S. Government may violate any copyrights that
# exist in this work.

# Copyright (c) 2021 Massachusetts Institute of Technology
# SPDX short identifier: MIT

# Developed as part of: SimAEN, 2021
*/

pipeline {
    agent {
        docker {
            image 'node:14-buster' 
            args '-w /home/node -u root -e proxy=http://llproxy.llan.ll.mit.edu:8080 -e https-proxy=http://llproxy.llan.ll.mit.edu:8080 -e https_proxy=http://llproxy.llan.ll.mit.edu:8080'
        }
    }
    environment {
        DEBIAN_FRONTEND = 'noninteractive'
        GIT_COMMITTER_EMAIL = """${sh(
            script: "git --no-pager show -s --format='%ae'",
            returnStdout: true
            ).trim()}"""        
    }
    stages {
        stage('debug') {
            steps {
                sh 'printenv'
            }
        }
        stage('build') {
            when {
                not {
                    anyOf {
                        branch 'master';
                        tag pattern: "^[0-9]\\d*\\.\\d+\\.\\d+\$", comparator: "REGEXP";
                    }
                }
            }
            steps {
                checkout scm
                dir ('simaen-web') {
                    sh 'npm ci'
                    sh 'npm run build'
                    sh 'npm run test'
                }
            }
        }
        stage('build for dev') {
            //when {  expression { false } }  //disable this stage temporarily
            when { branch 'master' }
            steps {
                checkout scm
                dir ('simaen-web') {
                    sh 'npm ci'
                    sh 'REACT_APP_API_URL=https://cdc-simaen.llan.ll.mit.edu/api/ PUBLIC_URL=https://cdc-simaen.llan.ll.mit.edu npm run build'
                    sh 'npm run test'
                }
            }
        }
        stage('build for prod') {
            //when {  expression { false } }  //disable this stage temporarily
            when { tag pattern: "^[0-9]\\d*\\.\\d+\\.\\d+\$", comparator: "REGEXP" }
            steps {
                checkout scm
                dir ('simaen-web') {
                    sh 'npm ci'
                    sh 'REACT_APP_API_URL=https://cdc-simaen.hadr.ll.mit.edu/api/ PUBLIC_URL=https://cdc-simaen.hadr.ll.mit.edu npm run build'
                    sh 'npm run test'
                }
            }
        }
        stage('lazy rsync install') {
            when {
                anyOf {
                    branch 'master';
                    tag pattern: "^[0-9]\\d*\\.\\d+\\.\\d+\$", comparator: "REGEXP";
                }
            }
            steps{
                sh 'export http_proxy=http://llproxy.llan.ll.mit.edu:8080 && apt-get update && apt-get install -y rsync'
            }
        }
        stage('deploy dev') {
            //when {  expression { false } }  //disable this stage temporarily
            when { branch 'master' }
            steps {
                sshagent (credentials: ['g21jenkins']) {
                    sh 'rsync -avh -e "ssh -o StrictHostKeyChecking=no" --delete --no-owner --no-group --rsync-path="sudo rsync" simaen-web/build/ g21jenkins@cdc-simaen.llan.ll.mit.edu:/var/www/html/'
                }
            }
        }
        stage('deploy prod') {
            //when {  expression { false } }  //disable this stage temporarily
            when { tag pattern: "^[0-9]\\d*\\.\\d+\\.\\d+\$", comparator: "REGEXP" }
            steps {
                sshagent (credentials: ['g21jenkins']) {
                    sh 'rsync -avh -e "ssh -o StrictHostKeyChecking=no" --delete --no-owner --no-group --rsync-path="sudo rsync" simaen-web/build/ g21jenkins@cdc-simaen.hadr.ll.mit.edu:/var/www/html/'
                }
            }
        }
    }
    post {
        failure {
            script {                    
                if ( env.BRANCH_NAME == 'master' || env.BRANCH_NAME ==~ "^[0-9]\\d*\\.\\d+\\.\\d+\$" ) {
                    mail to: "simaen-support@ll.mit.edu",
                    subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                    body: "Build Failed ${env.RUN_DISPLAY_URL}"
                } else {
                    mail to: "${env.GIT_COMMITTER_EMAIL}",
                    subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                    body: "Build Failed ${env.RUN_DISPLAY_URL}"
                }
            }
        }
        success {
            script {
                if (env.BRANCH_NAME ==~ "^[0-9]\\d*\\.\\d+\\.\\d+\$" ) {
                    mail to: "simaen-support@ll.mit.edu",
                    subject: "Successful Deployment: ${currentBuild.fullDisplayName}",
                    body: "Build Deployed ${env.RUN_DISPLAY_URL}"
                }
            }
        }
    }
}
